// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH8uk6ku1Vrnk6M1IcJve-eKtki7S1cHA',
    appId: '1:153583284954:web:2ec0a223f6ae8e52e32be3',
    messagingSenderId: '153583284954',
    projectId: 'mobile-project-bookstore',
    authDomain: 'mobile-project-bookstore.firebaseapp.com',
    storageBucket: 'mobile-project-bookstore.firebasestorage.app',
    measurementId: 'G-YW4XR2VXKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcLT_gbjhmf7muGmcPIS7btaBeSvlwau0',
    appId: '1:153583284954:android:fcf48b0c666aae3de32be3',
    messagingSenderId: '153583284954',
    projectId: 'mobile-project-bookstore',
    storageBucket: 'mobile-project-bookstore.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCROIEAPW0B6hYifzcP_0VIs6DA7E3SX_E',
    appId: '1:153583284954:ios:f75e287b93bb6d9ce32be3',
    messagingSenderId: '153583284954',
    projectId: 'mobile-project-bookstore',
    storageBucket: 'mobile-project-bookstore.firebasestorage.app',
    iosBundleId: 'com.example.mobileAppProjectBookstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCROIEAPW0B6hYifzcP_0VIs6DA7E3SX_E',
    appId: '1:153583284954:ios:f75e287b93bb6d9ce32be3',
    messagingSenderId: '153583284954',
    projectId: 'mobile-project-bookstore',
    storageBucket: 'mobile-project-bookstore.firebasestorage.app',
    iosBundleId: 'com.example.mobileAppProjectBookstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH8uk6ku1Vrnk6M1IcJve-eKtki7S1cHA',
    appId: '1:153583284954:web:1aa59a4908fa5bf7e32be3',
    messagingSenderId: '153583284954',
    projectId: 'mobile-project-bookstore',
    authDomain: 'mobile-project-bookstore.firebaseapp.com',
    storageBucket: 'mobile-project-bookstore.firebasestorage.app',
    measurementId: 'G-VDYJW2L2SG',
  );
}